[tox]
min_version = 4.25
requires =
    tox-uv>=1

env_list =
    py3.{10-13}-vtk_latest

[testenv]
# ============= basic settings =============
description = Run the tests for python {basepython}
package =
    cov: editable # Otherwise, the coverage is not computed correctly
    !cov: wheel
wheel_build_env = .pkg

passenv =
    PYVISTA*
    TRAME*
    JUPYTER*
    PLOT_SKIP*
    DISPLAY
    XAUTHORITY
    ALLOW_PLOTTING
    PYTEST*
    GITHUB*
    *SSL*
    COVERAGE*
    CI*
    MESA*
    VTK*
    DISPLAY*
    UV_INDEX
    PIP_INDEX_URL
    PIP_TRUSTED_HOST
    PLAYWRIGHT*

setenv =
    PYTEST_ADDOPTS = --color=yes -v 

# ============= specific settings =============
ignore_errors = True # to keep continuing commands if one fails
recreate = True # since we uninstall xdist, the second time tox is launched, xdist would not be found (at least for local runs)
allowlist_externals =
    playwright

# ============= dependencies =============
dependency_groups = tests
extras = vtksz
deps =
    vtk_9.2.2: vtk == 9.2.2

# =========== commands ===========
extra_setup_commands = 
    playwright install chromium
commands_pre = 
    pyvista report --gpu --downloads
coverage_command = 
    coverage run --parallel-mode --branch --source=pytest_pyvista -m {[testenv]pytest_cmd} 
pytest_cmd =
    pytest {posargs}

commands = 
    !no_xdist-!cov: {[testenv]pytest_cmd} 
    !no_xdist-cov: {[testenv]coverage_command}

    no_xdist: uv pip uninstall pytest-xdist
    no_xdist-!cov: {[testenv]pytest_cmd} -k test_arguments 
    no_xdist-cov: {[testenv]coverage_command} -k test_arguments 

[testenv:coverage]
base = 
description = Gather coverage report inside a single file. Useful in CI.
skip_install = true
deps = coverage
commands =
    coverage combine
    coverage xml -o coverage.xml

[testenv:downstream]
description = Run pyvista test suite on master branch using the current pytest-pyvista
setenv =
    {[testenv]setenv}
    PYVISTA_HOME = {temp_dir}{/}pyvista


# ============= specific settings =============
recreate = true  # to cleanup the git repository, otherwise cloning with existing folder fails
recreate_commands = python -c "import shutil,os,stat;shutil.rmtree(os.environ['PYVISTA_HOME'], onerror=lambda func, path, _: (os.chmod(path, stat.S_IWRITE), func(path)))"
allowlist_externals =
    git

# ============= dependencies =============
# all dependencies are skipped since it is done in commands_pre
skip_install = true 
dependency_groups =
extras =  

# =========== commands ===========
commands_pre = 
    # install pyvista main branch with deps
    git clone --depth=1 https://github.com/pyvista/pyvista.git --branch main --single-branch {env:PYVISTA_HOME} 
    uv pip install --editable {env:PYVISTA_HOME} --group test --directory {env:PYVISTA_HOME}

    # install local pytest-pyvista. Should only override the previously installed version
    uv pip install .
    {[testenv]commands_pre}
commands =
    pytest -v --allow_useless_fixture --generated_image_dir gen_dir {env:PYVISTA_HOME}{/}tests{/}plotting --disallow_unused_cache -n8