"""pyvista-pytest documentation configuration."""

from __future__ import annotations

from datetime import datetime

from pytest_pyvista import __version__

extensions = [
    "notfound.extension",
    "sphinx.ext.autosummary",
    "sphinx.ext.ifconfig",
    "sphinx_copybutton",
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
# source_suffix = ['.rst', '.md']  # noqa: ERA001
source_suffix = ".rst"

# The encoding of source files.
# source_encoding = 'utf-8-sig'  # noqa: ERA001

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "pytest-pyvista"
copyright = f"{datetime.now().year}, PyVista"  # noqa: A001, DTZ005
author = "The PyVista developers"

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
release = version = __version__

# The language for content autogenerated by Sphinx.
language = "en"

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
# today = ''  # noqa: ERA001
# Else, today_fmt is used as the format for a strftime call.
# today_fmt = '%B %d, %Y'  # noqa: ERA001

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ["_build"]

# The reST default role (used for this markup: `text`) to use for all
# documents.
# default_role = None  # noqa: ERA001

# If true, '()' will be appended to :func: etc. cross-reference text.
# add_function_parentheses = True  # noqa: ERA001

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
# add_module_names = True  # noqa: ERA001

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
# show_authors = False  # noqa: ERA001

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# A list of ignored prefixes for module index sorting.
# modindex_common_prefix = []  # noqa: ERA001

# If true, keep warnings as 'system message' paragraphs in the built documents.
# keep_warnings = False  # noqa: ERA001

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = "pydata_sphinx_theme"
# html_theme_path = [pydata_sphinx_theme.get_html_theme_path()]  # noqa: ERA001
html_context = {
    "logo": "https://docs.pyvista.org/_static/pyvista_logo_sm.png",
    "github_user": "pyvista",
    "github_repo": "pytest-pyvista",
    "github_version": "main",
    "doc_path": "doc",
}
html_show_sourcelink = False

html_theme_options = {
    "show_prev_next": False,
    "github_url": "https://github.com/pyvista/pytest-pyvista",
    "collapse_navigation": True,
    "use_edit_page_button": True,
    "icon_links": [
        {
            "name": "Slack Community",
            "url": "http://slack.pyvista.org",
            "icon": "fab fa-slack",
        },
        {
            "name": "Support",
            "url": "https://github.com/pyvista/pyvista/discussions",
            "icon": "fa fa-comment fa-fw",
        },
        {
            "name": "Contributing",
            "url": "https://github.com/pyvista/pyvista/blob/main/CONTRIBUTING.rst",
            "icon": "fa fa-gavel fa-fw",
        },
    ],
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named 'default.css' will overwrite the builtin 'default.css'.
html_static_path = ["_static"]


# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation.
# html_extra_path = []  # noqa: ERA001

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
# html_last_updated_fmt = '%b %d, %Y'  # noqa: ERA001

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
# html_use_smartypants = True  # noqa: ERA001

# Custom sidebar templates, maps document names to template names.
# html_sidebars = {}  # noqa: ERA001

# Additional templates that should be rendered to pages, maps page names to
# template names.
# html_additional_pages = {}  # noqa: ERA001

# If false, no module index is generated.
# html_domain_indices = True  # noqa: ERA001

# If false, no index is generated.
# html_use_index = True  # noqa: ERA001

# If true, the index is split into individual pages for each letter.
# html_split_index = False  # noqa: ERA001

# If true, links to the reST sources are added to the pages.
# html_show_sourcelink = True  # noqa: ERA001

# If true, 'Created using Sphinx' is shown in the HTML footer. Default is True.
# html_show_sphinx = True  # noqa: ERA001

# If true, '(C) Copyright ...' is shown in the HTML footer. Default is True.
# html_show_copyright = True  # noqa: ERA001

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
# html_use_opensearch = ''  # noqa: ERA001

# This is the file name suffix for HTML files (e.g. '.xhtml').
# html_file_suffix = None  # noqa: ERA001

# Language to be used for generating the HTML full-text search index.
# Sphinx supports the following languages:
#   'da', 'de', 'en', 'es', 'fi', 'fr', 'hu', 'it', 'ja'
#   'nl', 'no', 'pt', 'ro', 'ru', 'sv', 'tr'
# html_search_language = 'en'  # noqa: ERA001

# A dictionary with options for the search language support, empty by default.
# Now only 'ja' uses this config value
# html_search_options = {'type': 'default'}  # noqa: ERA001

# The name of a javascript file (relative to the configuration directory) that
# implements a search results scorer. If empty, the default will be used.
# html_search_scorer = 'scorer.js'  # noqa: ERA001

# Output file base name for HTML help builder.
htmlhelp_basename = "pytest-cookiecutterplugin_namedoc"

# -- Options for LaTeX output ---------------------------------------------
# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (
        master_doc,
        "pytest-cookiecutterplugin_name.tex",
        "pytest-\\{\\{cookiecutter.plugin\\_name\\}\\} Documentation",
        "\\{\\{cookiecutter.full\\_name\\}\\}",
        "manual",
    ),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
# latex_logo = None  # noqa: ERA001

# For 'manual' documents, if this is true, then toplevel headings are parts,
# not chapters.
# latex_use_parts = False  # noqa: ERA001

# If true, show page references after internal links.
# latex_show_pagerefs = False  # noqa: ERA001

# If true, show URL addresses after external links.
# latex_show_urls = False  # noqa: ERA001

# Documents to append as an appendix to all manuals.
# latex_appendices = []  # noqa: ERA001

# If false, no module index is generated.
# latex_domain_indices = True  # noqa: ERA001


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (
        master_doc,
        "pytest-cookiecutterplugin_name",
        "pytest-pyvista Documentation",
        [author],
        1,
    )
]

# If true, show URL addresses after external links.
# man_show_urls = False  # noqa: ERA001


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "pytest-cookiecutterplugin_name",
        "pytest-pyvista Documentation",
        author,
        "pytest-cookiecutterplugin_name",
        "One line description of project.",
        "Miscellaneous",
    ),
]

# Documents to append as an appendix to all manuals.
# texinfo_appendices = []  # noqa: ERA001

# If false, no module index is generated.
# texinfo_domain_indices = True  # noqa: ERA001

# How to display URL addresses: 'footnote', 'no', or 'inline'.
# texinfo_show_urls = 'footnote'  # noqa: ERA001

# If true, do not generate a @detailmenu in the 'Top' node's menu.
# texinfo_no_detailmenu = False  # noqa: ERA001
